<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Relight.Core\Relight.Core.csproj" />
    <ProjectReference Include="..\..\src\Relight.Engine\Relight.Engine.csproj" />
    <ProjectReference Include="..\..\src\Relight.Storage\Relight.Storage.csproj" />
    <ProjectReference Include="..\..\src\Relight.Windows\Relight.Windows.csproj" />
    <ProjectReference Include="..\Relight.TestTarget\Relight.TestTarget.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
