using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using Relight.Core;

namespace Relight.Storage;

public enum EventSeverity { Debug, Information, Warning, Error }

public enum OperationalEventKind
{
    Startup,
    Shutdown,
    TargetObserved,
    TargetDisappeared,
    StateChanged,
    DetectionUnavailable,
    LaunchReserved,
    LaunchDispatched,
    LaunchFailed,
    AppearanceTimedOut,
    ObservationStarted,
    ObservationInterrupted,
    ObservationCompleted,
    LockoutEntered,
    RecoveryRearmed,
    ManualAction,
    ProtectionPaused,
    ProtectionResumed,
    RecoveryReset,
    ExplicitStartRequested,
    ExplicitStartDispatched,
    ExplicitStartUncertain,
    PolicyChanged,
    MonitoringGap,
    MonitoringRestored,
    StorageDegraded
}

/// <summary>
/// Structured facts only. Arguments, environment variables, window contents,
/// chat text and raw exception messages have no field in this schema.
/// </summary>
public sealed record OperationalEvent(
    DateTimeOffset OccurredUtc,
    Guid EventId,
    EventSeverity Severity,
    OperationalEventKind Kind,
    Guid? ProfileId = null,
    string? ProfileName = null,
    Guid? EpisodeId = null,
    Guid? OperationId = null,
    RecoveryState? PreviousState = null,
    RecoveryState? NewState = null,
    ObservationOrigin? Origin = null,
    int? AttemptNumber = null,
    int? AttemptLimit = null,
    string? ProcessIdentity = null,
    int? NativeErrorCode = null);

public sealed record EventJournalStatus(
    bool Degraded,
    int BufferedCount,
    long DroppedCount,
    string? Diagnostic);

public interface IOperationalEventWriter
{
    Task<EventJournalStatus> AppendAsync(OperationalEvent entry,
        CancellationToken cancellationToken = default);
    Task<EventJournalStatus> GetStatusAsync(CancellationToken cancellationToken = default);
}

/// <summary>
/// Asynchronous JSON Lines journal with bounded failure buffering. Retention
/// only touches regular files with names generated by this journal.
/// </summary>
public sealed class OperationalEventJournal : IOperationalEventWriter, IDisposable
{
    internal static readonly Regex OwnedFileName = new(
        @"^events-\d{8}T\d{13}Z-[0-9a-f]{32}\.jsonl$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);
    internal static readonly JsonSerializerOptions Json = CreateJsonOptions();
    private readonly string _directory;
    private readonly int _retentionDays;
    private readonly long _maximumBytes;
    private readonly long _rotationBytes;
    private readonly int _bufferLimit;
    private readonly SemaphoreSlim _gate = new(1, 1);
    private readonly Queue<OperationalEvent> _buffer = new();
    private string? _activePath;
    private long _activeBytes;
    private long _droppedCount;
    private bool _degraded;
    private string? _diagnostic;

    public OperationalEventJournal(string dataDirectory, GlobalConfiguration settings,
        int bufferLimit = 1000)
    {
        if (string.IsNullOrWhiteSpace(dataDirectory))
            throw new ArgumentException("Data directory is required.", nameof(dataDirectory));
        ArgumentNullException.ThrowIfNull(settings);
        if (settings.LogRetentionDays is < 1 or > 3650 ||
            settings.MaximumLogBytes < 1_048_576 ||
            settings.LogRotationBytes is < 65_536 ||
            settings.LogRotationBytes > settings.MaximumLogBytes ||
            bufferLimit < 1)
            throw new ArgumentOutOfRangeException(nameof(settings));
        _directory = Path.Combine(Path.GetFullPath(dataDirectory), "Logs");
        _retentionDays = settings.LogRetentionDays;
        _maximumBytes = settings.MaximumLogBytes;
        _rotationBytes = settings.LogRotationBytes;
        _bufferLimit = bufferLimit;
    }

    public async Task<EventJournalStatus> AppendAsync(OperationalEvent entry,
        CancellationToken cancellationToken = default)
    {
        Validate(entry);
        await _gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            try
            {
                EnsureDirectory();
                while (_buffer.Count > 0)
                {
                    await AppendOneAsync(_buffer.Peek(), cancellationToken).ConfigureAwait(false);
                    _buffer.Dequeue();
                }
                await AppendOneAsync(entry, cancellationToken).ConfigureAwait(false);
                _degraded = false;
                _diagnostic = null;
            }
            catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
            {
                // This event was not confirmed durable. Keep its ID for a later
                // retry; readers can de-duplicate an interrupted partial write.
                Buffer(entry);
                throw;
            }
            catch (Exception error) when (error is IOException or UnauthorizedAccessException)
            {
                Buffer(entry);
                _degraded = true;
                _diagnostic = $"Event log unavailable ({error.GetType().Name}).";
                return Status();
            }

            try { EnforceRetention(); }
            catch (Exception error) when (error is IOException or UnauthorizedAccessException)
            {
                // The event itself was written. Do not buffer it again.
                _degraded = true;
                _diagnostic = $"Event log retention failed ({error.GetType().Name}).";
            }
            return Status();
        }
        finally { _gate.Release(); }
    }

    public async Task<EventJournalStatus> GetStatusAsync(CancellationToken cancellationToken = default)
    {
        await _gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try { return Status(); }
        finally { _gate.Release(); }
    }

    private EventJournalStatus Status() =>
        new(_degraded, _buffer.Count, _droppedCount, _diagnostic);

    private void Buffer(OperationalEvent entry)
    {
        if (_buffer.Count == _bufferLimit)
        {
            _buffer.Dequeue();
            _droppedCount++;
        }
        _buffer.Enqueue(entry);
    }

    private void EnsureDirectory()
    {
        Directory.CreateDirectory(_directory);
        if ((File.GetAttributes(_directory) & FileAttributes.ReparsePoint) != 0)
            throw new IOException("The log directory cannot be a reparse point.");
    }

    private async Task AppendOneAsync(OperationalEvent entry, CancellationToken cancellationToken)
    {
        byte[] line = Encoding.UTF8.GetBytes(JsonSerializer.Serialize(entry, Json) + "\n");
        if (_activePath is null || _activeBytes + line.Length > _rotationBytes)
        {
            _activePath = Path.Combine(_directory,
                $"events-{DateTimeOffset.UtcNow:yyyyMMdd'T'HHmmssfffffff'Z'}-{Guid.NewGuid():N}.jsonl");
            _activeBytes = 0;
        }
        using var stream = new FileStream(_activePath, FileMode.Append, FileAccess.Write,
            FileShare.Read, 4096, FileOptions.Asynchronous | FileOptions.WriteThrough);
        await stream.WriteAsync(line, cancellationToken).ConfigureAwait(false);
        await stream.FlushAsync(cancellationToken).ConfigureAwait(false);
        _activeBytes = stream.Length;
    }

    private void EnforceRetention()
    {
        DateTime cutoff = DateTime.UtcNow.AddDays(-_retentionDays);
        var owned = Directory.EnumerateFiles(_directory, "events-*.jsonl", SearchOption.TopDirectoryOnly)
            .Where(path => OwnedFileName.IsMatch(Path.GetFileName(path)))
            .Select(path => new FileInfo(path))
            .Where(file => (file.Attributes & FileAttributes.ReparsePoint) == 0)
            .OrderBy(file => file.LastWriteTimeUtc)
            .ToList();
        long total = owned.Sum(file => file.Length);
        foreach (FileInfo file in owned)
        {
            if (string.Equals(file.FullName, _activePath, StringComparison.OrdinalIgnoreCase))
                continue;
            if (file.LastWriteTimeUtc >= cutoff && total <= _maximumBytes)
                break;
            long length = file.Length;
            file.Delete();
            total -= length;
        }
    }

    private static void Validate(OperationalEvent entry)
    {
        ArgumentNullException.ThrowIfNull(entry);
        if (entry.EventId == Guid.Empty || entry.OccurredUtc.Offset != TimeSpan.Zero ||
            !Enum.IsDefined(entry.Kind) || !Enum.IsDefined(entry.Severity) ||
            entry.ProfileId == Guid.Empty || entry.EpisodeId == Guid.Empty ||
            entry.OperationId == Guid.Empty ||
            entry.AttemptNumber is < 0 || entry.AttemptLimit is < 0)
            throw new ArgumentException("Operational event fields are invalid.", nameof(entry));
    }

    private static JsonSerializerOptions CreateJsonOptions()
    {
        var options = new JsonSerializerOptions(JsonSerializerDefaults.Web);
        options.Converters.Add(new JsonStringEnumConverter(allowIntegerValues: false));
        return options;
    }

    public void Dispose() => _gate.Dispose();
}
